### ISSUE TITLE
请问这个项目是否有相关论文可以拜读一下呢

### ISSUE THREAD

**Issue by kuaileecho** [yue2388253/FlexTAS#1]

**Comment by pang554** [comment]
请问你找到了吗，我也还没找到，难道没有吗。

**Comment by pang554** [comment]
你好，自己训练的模型和作者给的最优模型结果相差了一倍，你有没有遇到这种情况呢。这差距会不会太大了呢。。

**Comment by yue2388253** [comment]
> 请问你找到了吗，我也还没找到，难道没有吗。

目前还没有公开哈

**Comment by yue2388253** [comment]
> 你好，自己训练的模型和作者给的最优模型结果相差了一倍，你有没有遇到这种情况呢。这差距会不会太大了呢。。

请问你是怎么训练的呢？

**Comment by pang554** [comment]
&nbsp; &nbsp; 很高兴能收到作者的邮件。
&nbsp; &nbsp; 关于训练结果的事情我问了导师，导师说跟设备有关，我的配置太垃圾了。。而且就在我写这封邮件的时候忽然回忆起，我当时想先试一下，为了节省时间就把时间步缩小了很多，后面就把这茬给忘了。好像是这样，今天我会再训练一下看看结果。
&nbsp; &nbsp; 关于您提到的论文目前还没有公开，是指论文之后会发只是现在还没公开的意思吗。感谢作者的回复。







---原始邮件---
发件人: "Jiashuo ***@***.***&gt;
发送时间: 2024年8月8日(周四) 下午5:24
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [yue2388253/FlexTAS] 请问这个项目是否有相关论文可以拜读一下呢 (Issue #1)




  
你好，自己训练的模型和作者给的最优模型结果相差了一倍，你有没有遇到这种情况呢。这差距会不会太大了呢。。
  
请问你是怎么训练的呢？

**Comment by yue2388253** [comment]
> &nbsp; &nbsp; 很高兴能收到作者的邮件。 &nbsp; &nbsp; 关于训练结果的事情我问了导师，导师说跟设备有关，我的配置太垃圾了。。而且就在我写这封邮件的时候忽然回忆起，我当时想先试一下，为了节省时间就把时间步缩小了很多，后面就把这茬给忘了。好像是这样，今天我会再训练一下看看结果。 &nbsp; &nbsp; 关于您提到的论文目前还没有公开，是指论文之后会发只是现在还没公开的意思吗。感谢作者的回复。
> […](#)
> ---原始邮件--- 发件人: "Jiashuo ***@***.***&gt; 发送时间: 2024年8月8日(周四) 下午5:24 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [yue2388253/FlexTAS] 请问这个项目是否有相关论文可以拜读一下呢 (Issue #1) 你好，自己训练的模型和作者给的最优模型结果相差了一倍，你有没有遇到这种情况呢。这差距会不会太大了呢。。 请问你是怎么训练的呢？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

timestep 肯定会显著影响训练模型的性能的，应该设置为一个比较大的值，当然这也会花更多时间训练，具体多少我也忘记了，大概2M？

论文发表后会公开的。

**Comment by pang554** [comment]
好的我会再训练的，感谢作者的回复。



---原始邮件---
发件人: "Jiashuo ***@***.***&gt;
发送时间: 2024年8月8日(周四) 下午5:42
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [yue2388253/FlexTAS] 请问这个项目是否有相关论文可以拜读一下呢 (Issue #1)




  
&nbsp; &nbsp; 很高兴能收到作者的邮件。 &nbsp; &nbsp; 关于训练结果的事情我问了导师，导师说跟设备有关，我的配置太垃圾了。。而且就在我写这封邮件的时候忽然回忆起，我当时想先试一下，为了节省时间就把时间步缩小了很多，后面就把这茬给忘了。好像是这样，今天我会再训练一下看看结果。 &nbsp; &nbsp; 关于您提到的论文目前还没有公开，是指论文之后会发只是现在还没公开的意思吗。感谢作者的回复。
 …
 ---原始邮件--- 发件人: "Jiashuo @.&gt; 发送时间: 2024年8月8日(周四) 下午5:24 收件人: @.&gt;; 抄送: @.@.&gt;; 主题: Re: [yue2388253/FlexTAS] 请问这个项目是否有相关论文可以拜读一下呢 (Issue #1) 你好，自己训练的模型和作者给的最优模型结果相差了一倍，你有没有遇到这种情况呢。这差距会不会太大了呢。。 请问你是怎么训练的呢？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.***&gt;
  
timestep 肯定会显著影响训练模型的性能的，应该设置为一个比较大的值，当然这也会花更多时间训练，具体多少我也忘记了，大概2M？
 
论文发表后会公开的。

**Comment by zthsp** [comment]
你好，请问目前论文公开了吗？是否可以拜读一下

**Comment by zthsp** [comment]
问哈 论文中图一中的Stream class 1 2 3 是指的什么

![Image](https://github.com/user-attachments/assets/480c0546-6424-497f-921c-19145d215af7)

**Comment by yue2388253** [comment]
> 问哈 论文中图一中的Stream class 1 2 3 是指的什么
> 
> ![Image](https://github.com/user-attachments/assets/480c0546-6424-497f-921c-19145d215af7)

论文中受限于篇幅没办法详细展开。
其分别指IEC/IEEE 60802 Use cases 文件中Figure 25, 26, 29的几种情况，由于业务流周期差异很大而导致的GCL迅速膨胀（论文中称为 GCL expansion）的问题。

**Comment by zthsp** [comment]
作者你好，我想请教你个问题关于FlexTAS论文代码的，我想问哈我在你代码的基础上新添加一个流选择动作，形成一个上下层的分层强化学习，上层进行调度流的选择，下层进行您原论文的门控选择，其余东西保持不变，这样的动作设计你觉得有最优解吗？能收敛吗？希望听听您的看法。 望回复




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yue2388253/FlexTAS"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2025年6月3日(星期二) 下午4:01
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [yue2388253/FlexTAS] 请问这个项目是否有相关论文可以拜读一下呢 (Issue #1)



yue2388253 left a comment (yue2388253/FlexTAS#1)
  
问哈 论文中图一中的Stream class 1 2 3 是指的什么
 
image.png (view on web)
  
论文中受限于篇幅没办法详细展开。
 其分别指IEC/IEEE 60802 Use cases 文件中Figure 25, 26, 29的几种情况，由于业务流周期差异很大而导致的GCL迅速膨胀（论文中称为 GCL expansion）的问题。
